### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by andreasloe** [stenub/wlan_switcher#1]
After installing the file I and running it I obtained the following error message
`File "wlan_switcher.py", line 116`
`    print(config_header, file=configfile)`
 `                                           ^`
`SyntaxError: invalid syntax`

**Comment by stenub** [comment]
which version of phyton are you using?

**Comment by andreasloe** [comment]
```
sudo python --version
Python 2.7.3

```

**Comment by stenub** [comment]
python3 is the thing you need! Please consult README!

**Comment by andreasloe** [comment]
Shame on me!

Now, I get 

```
File "wlan.py", line 61, in <module>
    import requests
```

and pip install requests or pip3 install requests does not help or are not found. I do not know how to install python3-pip (sudo apt-get install python3-pip and sudo apt-get install python-requests did not help).

**Comment by andreasloe** [comment]
OK, I think I made it. 
`sudo python3 -m easy_install pip`
and then 
`sudo pip-3.2 install requests`. Thank you! Now I get another error:

`File "wlan.py", line 61, in <module>`
`import requests`
`File "/usr/local/lib/python3.2/dist-packages/requests/__init__.py", line 52, in <module>` 
`from .packages.urllib3.contrib import pyopenssl`
`File "/usr/local/lib/python3.2/dist-packages/requests/packages/__init__.py", line 39, in <module>`
`from . import idna`
`File "/usr/local/lib/python3.2/dist-packages/requests/packages/idna/__init__.py", line 1, in` `<module>`
`from .core import *`
`File "/usr/local/lib/python3.2/dist-packages/requests/packages/idna/core.py", line 10`
`_unicode_dots_re = re.compile(u'[\u002e\u3002\uff0e\uff61]')`
`^`
`SyntaxError: invalid syntax`

**Comment by stenub** [comment]
how do you execute wlan_switcher.py ?

**Comment by andreasloe** [comment]
I changed the filename to wlan.py and I am running
`sudo python3 wlan.py`
(I want to extend the functionality.)

**Comment by stenub** [comment]
hm ok, that should work! do you use python3.4.2 or above?
what linux distribution are you using?

**Comment by andreasloe** [comment]
No!
`Python 3.2.3`
How can I upgrade?

**Comment by stenub** [comment]
what linux distribution are you using?

**Comment by andreasloe** [comment]
`Linux RPi 4.4.13+ #894 Mon Jun 13 12:43:26 BST 2016 armv6l`

**Comment by stenub** [comment]
ok, thats your kernel version, i assume you use raspian?
what returnes `cat /etc/debian_version`

please try `apt-get install python3.4`

**Comment by stenub** [comment]
btw please fully update your system with `apt-get dist-upgrade` and reboot, you are not running on the latest raspian kernel. After that `uname -a` should give you:
`Linux RPi 4.4.32+ #924 Tue Nov 15 18:06:42 GMT 2016 armv6l GNU/Linux`

**Comment by stenub** [comment]
perhaps i can help you via teamviewer for example?

**Comment by andreasloe** [comment]
I get
`cat /etc/debian_version`
`7.11`
and
`E: Paket python3.4 kann nicht gefunden werden.`
After dist-upgrade I have
`Linux XY 4.4.13+ #894 Mon Jun 13 12:43:26 BST 2016 armv6l`
I am running raspbian on a RPi 2B.

**Comment by stenub** [comment]
Your debian is (quite) old, your debian_version should be 8.0 
I think you are doing good if you upgrade your installation to debian jessie (8).

Now you have two possibilitys:

1.
If you have no configuration or personal files on your raspi, you better do a fresh install. 
Download: https://www.raspberrypi.org/downloads/raspbian/
Take the Raspian Jessie lite zip if you need no desktop environment and are mostly working via ssh on your raspi.
Install instructions (writing the image to your sd card) can be found here:
https://www.raspberrypi.org/documentation/installation/installing-images/README.md

2.
If you have not the chance to write an image to your sd card via a sd card writer and a second pc, you can also try to upgrade the installation by modifying the files in `/etc/apt/sources.list.d/` from `wheezy` to `jessie` and do a `apt-get update && apt-get upgrade`
This can last quite a long time depending on the speed of your internet connection and your sd card.

If you have nothing to loose i would prefer a fresh install via the image as mentioned first.

Feel free to ask me here if something is unclear.

**Comment by andreasloe** [comment]
I switched to jessie and everything is working right now. Thanks!

**Comment by stenub** [comment]
One last hint:
If you want to modify or extend my project please fork it to your own github repository so that i can track your edits. Perhaps i can help you here and there. 
With wlan_switcher you have full access to the speedport w724v so you can do everything that you also can do via the webgui of the router itself.
Please respect the GPL License and open your project!

Many Thanks!

**Comment by andreasloe** [comment]
Ich glaube, die meisten Speedport-Leute sprechen deutsch, oder? Ich habe mal angefangen ein paar Dinge anzupassen. Insbesondere möchte ich zum einen die Anrufliste automatisch auslesen und später das portforwarding auch automatisch kontrollieren (bei mir verschieben sich die IPs ständig, nervt). Blöd ist nur, dass ich noch nie richtig in python programmiert habe, mich in github nicht auskenne und JS auch nicht beherrsche. 

Also was die Anrufliste angeht, da habe ich schon angefangen ein paar Dinge anzupassen. Ich kapiere nur nicht, wieso bei mir der Response leer ist, obwohl ich ihn in Google (Entwicklertools) sehen - any idea? Hier kommt der Code:

`import requests`
`import hashlib`
<Edit> ... habe ich unten angehangen...

**Comment by andreasloe** [comment]
Kann man hier keine Datei anhängen? Doch...
[wlan.txt](https://github.com/stenub/wlan_switcher/files/679861/wlan.txt)

**Comment by stenub** [comment]
Funktioniert es denn die Wlan Module zu schalten? Wenn ja, vergleiche die Requests und Responses! Ich kann mich dunkel erinnern, dass der httoken mir änliche Probleme gemacht hat. Übergibst du nicht den token, macht der Router garnichts.
Ich würde dir empfehlen dich ein bisschen in github einzuarbeiten, dann ließe sich dein Code viel leichter lesen. Wenn du meinen Code forkst, dann lassen sich die Änderungen ganz genau tracen und somit leichter troubleshooten.

**Comment by andreasloe** [comment]
Ja, ich kann die WLAN-Module schalten. Ich habe nur keine Ahnung von python, wenn ich ehrlich bin und genau so wenig von json. Ich probiere das mit dem forken mal.

Ich habe das so gemacht: Ich ignoriere html- und sty-files und schaue nur auf die json-Dateien. Da gibt es eigentlich nur die, die schon in der Datei jetzt stehen. Anstand einer POST-Anforderung ist es bei der Anrufliste eine GET und ich sehe auch, was da drin steht (komischerweise zweimal _time, das muss Blödsinn sein, und dann zweimal _rand, die aber weiter nicht verwendet werden und natürlich httoken, aber das habe ich ja). Ich sehe in Google-Chrome-Entwickler einen "Response" und wenn ich den in python aufrufe, ist die Liste leer...

**Comment by stenub** [comment]
Versuche doch ein wenig python3 zu lernen, dann verstehst du auch was du da tust und kannst deine Probleme leichter eingrenzen. Phyton ist relativ leicht zu lernen und es lohnt sich definitiv, da man mit recht wenig Aufwand schnell viel erreichen kann. Ich würde dir ebenfalls empfehlen eine separate IDE zu installieren, mit der sich schneller und leichter entwickeln lässt. Ich verwende JetBrains pyCharm. Die Community Edition ist kostenlos und reicht für den Anfang allemal.

**Comment by andreasloe** [comment]
Das Problem ist weniger python(3), sondern die Logik hinter *.json. Die kapiere ich nicht.

**Comment by stenub** [comment]
json ist prinzipiell nur eine Art und Weise Key/Value Paare zu notieren. Im Web findet man aber genug Infos dazu.

**Comment by andreasloe** [comment]
Das heißt, die Datenübergabe bei speedport.ip funktioniert _ausschließlich_ über JSON-Objekte? So habe ich das auch Deinem Code entnommen. 

Mich wundert nur, wieso ich auf der Webseite selbst (Chrome->Entwickler->Code) unter Preview bzw unter Response die Angaben, die ich suche, sehe - nicht aber unter s.response, der sie eigentlich haben müsste.

**Comment by stenub** [comment]
Mal ne andere Frage: Wenn du die Telefonnummern hast, was willst du dann damit machen? In eine Datei schreiben? E-Mail versenden?
Beim portforwarding genau andersrum: Wo kommen die requests her und wie sehen sie aus?
Vielleicht kann ich das Script ja entsprechend erweitern.

**Comment by andreasloe** [comment]
Re Telefonnummern: Ich will die einfach mit dem Handy oder Tablet oder so sehen, ohne groß speedport.ip aufzumachen (auch von außerhalb). Beispielsweise könnte ich sie stündlich (cronjob) in eine mysql-Datenbank eintragen, die ich bei strato gehostet habe und dann auch extern (.htaccess, .htpasswd) abrufen kann.

Beim portforwarding ist das praktische Problem folgendes. Ich habe eine IP-Cam mit MAC-Nr, die intern Aufnahmen macht. Diese will ich per portforwarding nach außen geben (wieder gesichert mit .htaccess). Blöderweise "verstellt" speedport die Adresse desjenigen Rechners, der nach außen geöffnet wird. Statt des Ports 8085 der IP-Cam ist dann auf einmal der Port 8085 der VuUno nach außen offen. Ich muss dann immer einmal im Monat per Hand nachstellen. Das würde ich gern automatisieren.

**Comment by stenub** [comment]
Also die Geschichte mit Telefonnummern lässt sich gut machen, ich würde sie aber für den Anfang nur in umgekehrter Reihenfolge (letzte Anrufe zuerst) ganz simpel in eine html schreiben. Das mit dem sql import solltest du dann mit einem separaten Programm/Script auf dem Strato Server lösen.
Über eine noch dazu unverschlüsselte WAN Strecke direkt in eine SQL zu schreiben halte ich für sehr fehlerträchtig.

Die Geschichte mit dem Portforwarding lässt sich für mich nur durch UPNP erklären, soweit ich weiß unterstützt das der 724 aber nicht. 
Kann also nur noch ein Bug oder Defekt des Speedports sein. Wenn du den gemietet hast würde ich ihn tauschen lassen.
Dass Portforwardings sich einmal im Monat von selbst ändern halte ich für sehr dubios!

**Comment by andreasloe** [comment]
Ich meine das hier, siehe Screenshot. Der (interne) "Name" des Computers, dessen Port ich freigebe, ist angeschnitten. Das ist eine Auswahlliste und ich kann es mir auch nicht erklären - aber dieser interne Name hat sich mehrfach von selbst geändert. Ich musste von Hand nachjustieren.

Ich nutze aber als DHCP nicht den Router selbst, sondern einen Cisco Small Business SF 100D-08P - Switch.
<img width="500" alt="bildschirmfoto 2017-01-04 um 21 09 59" src="https://cloud.githubusercontent.com/assets/10688946/21657457/a708d926-d2c2-11e6-8283-890b47f37959.png">

**Comment by stenub** [comment]
Hallo Andreas,

ich war mal ein bisschen fleissig und habe deine gewünschte Anruflistenfunktion implementiert.
Du warst mit deinen Versuchen garnicht so weit weg. 
Wichtig ist, den Referer im Header beim get mitzugeben. Der httoken als Parameter darf auch nicht fehlen.
Viel Spaß damit!

**Comment by andreasloe** [comment]
Cool, probiere ich gleich mal aus - DANKE!

**Comment by andreasloe** [comment]
Klappt alles, super. Sollte nicht die Datei in wlan.py oder speedport.py umbenannt werden? Switcher passt ja nicht mehr, das wird doch demnächst ein Schweizer Messer für's Speedport 👍

**Comment by andreasloe** [comment]
Ich brauche nochmal Deine Hilfe. Ich will die Portfreigaben (die sich manchmal selbständig ändern?!) kontrollieren und automatisiert einstellen. Dazu habe ich mir mit Burp angeschaut, welcher Zugriff bei der Einstellung der Portfreigaben erfolgt. Das ist ein POST mit

`POST /data/Portforwarding.json HTTP/1.1
Content-Type: application/x-www-form-urlencoded`
`Referer: http://speedport.ip/html/content/internet/portforwarding.html?lang=de`
 
und dann kommt eine Zeile, die in etwa so aussieht:
`tcp_redirect_active%5B1%5D=1&tcp_redirect_active%5B2%5D=1&tcp_redirect_active%5B3%5D=1&tcp_redirect_active%5B4%5D=1&tcp_redirect_active%5B5%5D=1&tcp_public_from%5B1%5D=8082&tcp_public_from%5B2%5D=8084&tcp_public_from%5B3%5D=8081&tcp_public_from%5B4%5D=8083&tcp_public_from%5B5%5D=8080&tcp_public_to%5B1%5D=8082&tcp_public_to%5B2%5D=8084&tcp_public_to%5B3%5D=8081&tcp_public_to%5B4%5D=8083&tcp_public_to%5B5%5D=8080&tcp_private_dest%5B1%5D=8085&tcp_private_dest%5B2%5D=443&tcp_private_dest%5B3%5D=80&tcp_private_dest%5B4%5D=80&tcp_private_dest%5B5%5D=80&tcp_device%5B1%5D=199&tcp_device%5B2%5D=103&tcp_device%5B3%5D=109&tcp_device%5B4%5D=112&tcp_device%5B5%5D=113&tcpredirect_id%5B1%5D=3&tcpredirect_id%5B2%5D=13&tcpredirect_id%5B3%5D=11&tcpredirect_id%5B4%5D=12&tcpredirect_id%5B5%5D=14&httoken=436759627`

Die dreistelligen Zahlen da drin sind id's, die sich aus den IP-Nummern ableiten. Also habe ich in einem Code diese IPs ausgelesen und dann diesen POST nachgebaut. Das ging in etwa so

`		page = s.post(url_router + '/data/Login.json', data={'password': hashlib.md5(bytes(passwd_router, 'utf-8')).hexdigest(), 'showpw': '0', 'httoken': ''})`
`       httoken = re.findall('_httoken = (\d*);', s.get(url_router + '/html/content/overview/index.html?lang=de').text)[0]`
`       page = s.get(url_router + '/data/Overview.json', params={"_tn": httoken}, headers={'Referer': url_router + '/html/content/overview/index.html?lang=de'})`
`       page_decoded = json.loads(page.content.decode('utf-8'))`
`       for i in page_decoded:`
`            IP_zimmer += finde_mac("B8-27-XX-XX-XX-XX", i)`
`			 usw.                     `
`       daten = "tcp_redirect_active%5B1%5D=1&tcp_redirect_active%5B2%5D=1&tcp_redirect_active%5B3%5D=1&tcp_redirect_active%5B4%5D=1&tcp_redirect_active%5B5%5D=1&tcp_public_from%5B1%5D=8082&tcp_public_from%5B2%5D=8084&tcp_public_from%5B3%5D=8081&tcp_public_from%5B4%5D=8083&tcp_public_from%5B5%5D=8080&tcp_public_to%5B1%5D=8082&tcp_public_to%5B2%5D=8084&tcp_public_to%5B3%5D=8081&tcp_public_to%5B4%5D=8083&tcp_public_to%5B5%5D=8080&tcp_private_dest%5B1%5D=8085&tcp_private_dest%5B2%5D=443&tcp_private_dest%5B3%5D=80&tcp_private_dest%5B4%5D=80&tcp_private_dest%5B5%5D=80&tcp_device%5B1%5D=" + IP_zimmer + usw "&httoken=" + httoken`
`#		print(daten)`
`		page = s.post(url_router + '/data/Portforwarding.json', data={bytes(daten, 'utf-8')}, headers={'Referer': url_router + '/html/content/internet/portforwarding.html?lang=de', 'Content-Type': 'application/x-www-form-urlencoded'})`
 
Die Daten (IP-ids) werden richtig ausgerechnet, das habe ich überprüft: printe ich "daten", so ist das identisch dem, was ich mit Burp erhalten habe. Aber dann kommt eine Fehlermeldung, die ich nicht kapiere (siehe Anhang)

Was mache ich falsch?

**Comment by andreasloe** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
    yield
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 694, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./portfreigaben.py", line 72, in <module>
    main()
  File "./portfreigaben.py", line 69, in main
    page = s.post(url_router + '/data/Portforwarding.json', data={bytes(daten, 'utf-8')}, headers={'Referer': url_router + '/html/content/internet/portforwarding.html?lang=de'})
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 641, in send
    r.content
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 772, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 697, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

**Comment by stenub** [comment]
Hallo Andreas,

OpenSource funktioniert nur durch gegenseitiges neben und nehmen!
Bitte erstelle ein eigenes Repository und forke dann das meine. Beschäftige dich aktiv mit github, dann hat jeder was davon und ich kann mir auch besser ein Bild von deinem Code machen.

Vielen Dank!
